// Canonical card data for The Mahjong Mirror deck.
// Each card has a slug (URL), name, category, short meaning, and a longer description.

export const CARDS = [
  // ── Honor cards ──
  { slug: 'east', name: 'East', category: 'Honor', short: 'New beginnings · Spring',
    summary: 'East marks dawn, spring, and the first impulse toward action. In a reading it signals fresh starts, emerging ideas, and the energy to begin.',
    reading: 'When East appears, look for an opportunity just breaking the horizon — a move worth committing to before conditions fully clarify.' },
  { slug: 'south', name: 'South', category: 'Honor', short: 'Expansion · Visibility',
    summary: 'South is the sun at its peak — fame, warmth, and full expression. It signals a moment when your work is seen and your influence grows.',
    reading: 'South rewards confident action. Step into visibility. Claim the stage that is already being offered to you.' },
  { slug: 'west', name: 'West', category: 'Honor', short: 'Reflection · Harvest',
    summary: 'West is the settling hour — gathering in, counting what is real, and honoring what the season produced. It signals reflection and review.',
    reading: 'Slow down and take stock. The next right step will reveal itself only after you acknowledge what is already complete.' },
  { slug: 'north', name: 'North', category: 'Honor', short: 'Stillness · Wisdom',
    summary: 'North is winter — the quiet, inward season where instinct and ancestral knowledge sharpen. It signals patience and deep listening.',
    reading: 'This is not a time to push. The answer you seek arrives through stillness, dreams, or a trusted elder.' },
  { slug: 'red-dragon', name: 'Red Dragon', category: 'Honor', short: 'Success · Passion',
    summary: 'Red Dragon is recognition earned. It signals triumph, ambition fulfilled, and the heat of deeply felt desire.',
    reading: 'What you want is within reach. Claim it boldly — hesitation is the only remaining obstacle.' },
  { slug: 'green-dragon', name: 'Green Dragon', category: 'Honor', short: 'Growth · Fortune',
    summary: 'Green Dragon is money, abundance, and the steady unfolding of a plan that is finally working. It signals prosperity.',
    reading: 'A financial or career opportunity deserves your attention. The conditions for growth are genuinely in your favor.' },
  { slug: 'white-dragon', name: 'White Dragon', category: 'Honor', short: 'Purity · Clean slate',
    summary: 'White Dragon is the empty tile — a reset, a clearing, a blank page. It signals freedom from the weight of the past.',
    reading: 'Release what no longer serves you. You are being offered a genuine chance to begin again.' },

  // ── Suit cards ──
  { slug: 'heaven', name: 'Heaven', category: 'Suit', short: 'Destiny · Higher order',
    summary: 'Heaven is the largest pattern at work — fate, cosmic timing, and the forces beyond personal control.',
    reading: 'Trust the unfolding. What is happening is bigger than your current vantage point can show you.' },
  { slug: 'earth', name: 'Earth', category: 'Suit', short: 'Foundation · Stability',
    summary: 'Earth is the ground under your feet — security, patience, and the slow reliable work of building.',
    reading: 'Return to basics. The thing that will endure is being built right now, one careful decision at a time.' },
  { slug: 'fire', name: 'Fire', category: 'Suit', short: 'Passion · Urgency',
    summary: 'Fire is raw energy — desire, conflict, breakthrough. It illuminates and it consumes.',
    reading: 'Channel the heat deliberately. Left unexamined it burns; directed, it forges.' },
  { slug: 'water', name: 'Water', category: 'Suit', short: 'Emotion · Flow',
    summary: 'Water is feeling, intuition, and the path of least resistance that eventually wears stone smooth.',
    reading: 'Honor what you feel. The subtle current is showing you the route that force cannot open.' },
  { slug: 'dragon', name: 'Dragon', category: 'Suit', short: 'Power · Transformation',
    summary: 'The Dragon is potency itself — sovereign power, deep change, and the long game that arrives suddenly.',
    reading: 'A transformation is in motion. Do not resist it — align with it.' },
  { slug: 'phoenix', name: 'Phoenix', category: 'Suit', short: 'Renewal · Rising',
    summary: 'The Phoenix is rebirth after loss — the moment when what seemed ended reveals itself as transformed.',
    reading: 'What you thought was finished is returning in a stronger form. Welcome it back.' },
  { slug: 'tiger', name: 'Tiger', category: 'Suit', short: 'Courage · Instinct',
    summary: 'The Tiger is bold instinct, primal courage, and the moment that rewards the unhesitating move.',
    reading: 'Trust your first instinct. The situation is asking for decisiveness, not deliberation.' },
  { slug: 'tortoise', name: 'Tortoise', category: 'Suit', short: 'Endurance · Longevity',
    summary: 'The Tortoise is ancient patience — the quiet persistence that outlasts every faster rival.',
    reading: 'Slow is correct. The outcome you want is earned over time, not seized in one move.' },
  { slug: 'unicorn', name: 'Unicorn', category: 'Suit', short: 'Rarity · Blessing',
    summary: 'The Unicorn (qilin) is the rare arrival of grace — a blessing, a birth, a meeting that changes everything.',
    reading: 'Pay attention. A once-in-a-lifetime opportunity or encounter is near.' },
  { slug: 'peacock', name: 'Peacock', category: 'Suit', short: 'Beauty · Pride',
    summary: 'The Peacock is dignity, beauty, and the rightful display of what you have cultivated.',
    reading: 'Stand tall in what you have built. False modesty serves no one here.' },
  { slug: 'carp', name: 'Carp', category: 'Suit', short: 'Persistence · Ascent',
    summary: 'The Carp swims upstream to become a dragon — it is sustained effort crowned with breakthrough.',
    reading: 'Keep going. The transformation you are working toward is closer than it appears.' },
  { slug: 'toad', name: 'Toad', category: 'Suit', short: 'Wealth · Attraction',
    summary: 'The Three-Legged Toad is the classic Chinese symbol of wealth drawn to a prepared vessel.',
    reading: 'Abundance is arriving. Make sure you have the structure in place to receive it well.' },
  { slug: 'ducks', name: 'Ducks', category: 'Suit', short: 'Partnership · Loyalty',
    summary: 'Mandarin Ducks are lifelong pairing — romantic commitment, mutual choice, and fidelity.',
    reading: 'The bond you care about is real and mutually held. Act accordingly.' },
  { slug: 'insect', name: 'Insect', category: 'Suit', short: 'Small action · Patience',
    summary: 'The Insect is the small consistent contribution — the quiet work that compounds.',
    reading: 'Do not dismiss the small move. It matters more than the dramatic one you are imagining.' },
  { slug: 'jade', name: 'Jade', category: 'Suit', short: 'Virtue · Value',
    summary: 'Jade is value proven over time — integrity, heirloom worth, the green stone that outlasts fashion.',
    reading: 'What is genuinely valuable here is the relationship, principle, or commitment — not the transaction.' },
  { slug: 'pearl', name: 'Pearl', category: 'Suit', short: 'Hidden wisdom',
    summary: 'The Pearl is wisdom earned through friction — insight hidden inside experience.',
    reading: 'The lesson is already in your hands. Extract it before you move on.' },
  { slug: 'lotus', name: 'Lotus', category: 'Suit', short: 'Purity · Growth',
    summary: 'The Lotus rises clean from muddy water — it is spiritual clarity emerging from difficulty.',
    reading: 'You are clearer than you feel. What you went through is what made this clarity possible.' },
  { slug: 'peach', name: 'Peach', category: 'Suit', short: 'Longevity · Love',
    summary: 'The Peach is long life, romantic affection, and the sweetness of the well-lived year.',
    reading: 'Savor this moment. The season you are in is generous and wants to be enjoyed.' },
  { slug: 'mushroom', name: 'Mushroom', category: 'Suit', short: 'Longevity · Spirit',
    summary: 'The Lingzhi mushroom is spiritual longevity — life force cultivated and sustained.',
    reading: 'Tend to your energy. What you are being offered requires strength you must deliberately build.' },
  { slug: 'pine', name: 'Pine', category: 'Suit', short: 'Strength · Evergreen',
    summary: 'The Pine stands through winter — it is steadfast character and loyalty that does not waver.',
    reading: 'Hold your position. The person or principle you are standing for is worth the cost.' },
  { slug: 'willow', name: 'Willow', category: 'Suit', short: 'Grace · Flexibility',
    summary: 'The Willow bends without breaking — it is graceful adaptability under pressure.',
    reading: 'Adapt. The form is changing, but the essence of what you want can survive the change.' },
  { slug: 'seven-stars', name: 'Seven Stars', category: 'Suit', short: 'Guidance · Fate',
    summary: 'The Seven Stars of the Northern Dipper are the cosmic compass — destiny, guidance, life direction.',
    reading: 'You are being shown the way. The sign you were waiting for is already visible.' },
  { slug: 'knot', name: 'Knot', category: 'Suit', short: 'Connection · Complexity',
    summary: 'The Endless Knot is interwoven fate — relationships, karma, and the binding we choose.',
    reading: 'The situation is more connected than it appears. Do not try to cut cleanly through.' },
  { slug: 'lute', name: 'Lute', category: 'Suit', short: 'Harmony · Art',
    summary: 'The Lute is the cultivation of beauty — artistry, harmony, and the refined life.',
    reading: 'Attend to the aesthetic dimension. How something is done matters as much as whether it is done.' },
  { slug: 'sword', name: 'Sword', category: 'Suit', short: 'Clarity · Decision',
    summary: 'The Sword is the decisive cut — clarity of thought, truthful words, and the courage to choose.',
    reading: 'A decision is required. The discomfort of choosing is less than the cost of not choosing.' },
  { slug: 'door', name: 'Door', category: 'Suit', short: 'Threshold · Choice',
    summary: 'The Door is the moment of passage — opportunity, threshold, and the choice to enter or remain.',
    reading: 'An opening is in front of you. It will not stay open indefinitely.' },
  { slug: 'house', name: 'House', category: 'Suit', short: 'Home · Family',
    summary: 'The House is the domestic center — family, belonging, and the emotional architecture of home.',
    reading: 'Attend to home. The stability you need to move outward begins with the foundation indoors.' },

  // ── Guardian cards ──
  { slug: 'farmer', name: 'Farmer', category: 'Guardian', short: 'Labor · Seasons',
    summary: 'The Farmer is patient disciplined work tuned to the seasons — the long view.',
    reading: 'Plant what you will not harvest this season. The real yield is a year out.' },
  { slug: 'fisherman', name: 'Fisherman', category: 'Guardian', short: 'Patience · Timing',
    summary: 'The Fisherman waits for the right moment on the water — receptivity, skill, and timing.',
    reading: 'The opening is coming. Stay attentive — the moment will not announce itself.' },
  { slug: 'woodcutter', name: 'Woodcutter', category: 'Guardian', short: 'Effort · Simplicity',
    summary: 'The Woodcutter is honest effort — direct work, plain purpose, no performance required.',
    reading: 'Strip away the theater. The simplest honest version of this is the one that works.' },
  { slug: 'scholar', name: 'Scholar', category: 'Guardian', short: 'Study · Counsel',
    summary: 'The Scholar is accumulated knowledge and wise counsel — the teacher or mentor figure.',
    reading: 'Seek advice from someone with more experience than you. You do not need to figure this out alone.' },
  { slug: 'bamboo', name: 'Bamboo', category: 'Guardian', short: 'Resilience · Integrity',
    summary: 'Bamboo bends in the storm and springs back — resilience paired with moral uprightness.',
    reading: 'You are being tested on integrity. Hold the line without becoming rigid.' },
  { slug: 'chrysanthemum', name: 'Chrysanthemum', category: 'Guardian', short: 'Autumn · Dignity',
    summary: 'The Chrysanthemum is late-season dignity — grace, nobility, and the beauty that comes with maturity.',
    reading: 'This is not your beginning chapter. Bring the wisdom you have earned to this decision.' },
  { slug: 'orchid', name: 'Orchid', category: 'Guardian', short: 'Refinement · Friendship',
    summary: 'The Orchid is refined loyalty — the quiet friend, the subtle beauty, the understated presence.',
    reading: 'A quiet, loyal influence in your life matters more than the louder ones pulling on your attention.' },
  { slug: 'plum-blossom', name: 'Plum Blossom', category: 'Guardian', short: 'Hope · Early spring',
    summary: 'The Plum Blossom blooms through snow — it is courage, hope, and beauty arriving ahead of the season.',
    reading: 'You are early. Do not wait for everyone else to recognize what is already true.' },
];

export function getCard(slug) {
  return CARDS.find((c) => c.slug === slug);
}

export function getCardsByCategory(category) {
  return CARDS.filter((c) => c.category === category);
}
