// Canonical blog post index. Keep newest first.
// Any new published post must be added here AND have a matching page at /blog/posts/[slug].jsx.

export const POSTS = [
 {
 slug: 'opposites-attract-is-a-lie-fire-horse-love-2026',
 title: "'Opposites Attract' Is a Lie the Fire Horse Year Will Expose",
 excerpt: "The Fire Horse doesn't care about chemistry. It cares about compatibility. And the difference, for a lot of couples right now, is everything.",
 categories: ['Year of the Fire Horse'],
 date: 'May 4, 2026',
 isoDate: '2026-05-04',
 readTime: '8 min read',
 },
 {
 slug: 'feel-good-friday-your-career-is-not-your-cage',
 title: 'Feel Good Friday: Your Career Is Not Your Cage',
 excerpt: "If the Fire Horse year is amplifying frustration in your career, that's not a curse — it's a signal. A story from the reading table about what that signal means, and what to do with it.",
 categories: ['Year of the Fire Horse'],
 date: 'May 1, 2026',
 isoDate: '2026-05-01',
 readTime: '5 min read',
 },
 {
 slug: 'the-decision-framework-for-career-crossroads',
 title: 'The Decision Framework That Was Built for Career Crossroads',
 excerpt: "The Mahjong Mirror's four angles applied to career decisions. Most people skip three of them. The third angle — what's really opposing you — is where the breakthrough hides.",
 categories: ['Year of the Fire Horse'],
 date: 'Apr 29, 2026',
 isoDate: '2026-04-29',
 readTime: '8 min read',
 },
 {
 slug: 'fire-horse-will-blow-up-your-career',
 title: 'The Fire Horse Year Will Blow Up Your Career — One Way or Another',
 excerpt: 'Every 60 years, the Fire Horse tears through careers and industries and rewrites who wins. The pattern from 1906, 1966, and now 2026 is not subtle. The ones who thrive all did the same thing.',
 categories: ['Year of the Fire Horse'],
 date: 'Apr 27, 2026',
 isoDate: '2026-04-27',
 readTime: '7 min read',
 },
 {
 slug: 'feel-good-friday-the-horse-rewards-risk-takers',
 title: "Feel Good Friday: The Wealth You've Been Circling Around Is Closer Than You Think",
 excerpt: "The Horse doesn't reward the ones who wait for certainty. It rewards the ones who decide. The financial move you keep postponing? That's the one this year is asking you to make.",
 categories: ['Year of the Fire Horse'],
 date: 'Apr 24, 2026',
 isoDate: '2026-04-24',
 readTime: '5 min read',
 },
 {
 slug: 'how-to-know-if-this-is-the-year-for-you-to-take-a-financial-risk',
 title: 'How to Know If This Is the Year for You to Take a Financial Risk',
 excerpt: "The Fire Horse rewards movement, but not every move. Before you act, the Mahjong Mirror asks four questions that reveal whether a financial risk will change your life or just your account balance.",
 categories: ['Year of the Fire Horse'],
 date: 'Apr 22, 2026',
 isoDate: '2026-04-22',
 readTime: '7 min read',
 },
 {
 slug: 'money-in-the-year-of-the-fire-horse',
 title: "The Horse Is the Traveling Star, and It Carries Gold",
 excerpt: "The Fire Horse year is the most volatile wealth window in 60 years. The energy doesn't reward caution. It rewards movement, boldness, and the financial decisions most people are too afraid to make.",
 categories: ['Year of the Fire Horse', 'Chinese Astrology'],
 date: 'Apr 20, 2026',
 isoDate: '2026-04-20',
 readTime: '6 min read',
 },
 {
 slug: 'feel-good-friday-love-starts-with-knowing-yourself',
 title: "Feel Good Friday: The Best Relationship You'll Ever Have Starts in the Mirror",
 excerpt: "Before you can be the right partner, you have to know who you are. The Mahjong Mirror's Second Angle shows you where real love actually begins.",
 categories: ['Romance', 'Mahjong Reading'],
 date: 'Apr 17, 2026',
 isoDate: '2026-04-17',
 readTime: '6 min read',
 },
 {
 slug: 'planning-a-wedding-through-the-mahjong-mirror',
 title: 'The Mahjong Mirror Way to Plan a Wedding',
 excerpt: 'The biggest day of your life deserves more than a color scheme. The Mahjong Mirror asks two questions no wedding planner will: what does this day actually mean, and what do you really want from the marriage itself?',
 categories: ['Romance', 'Mahjong Reading'],
 date: 'Apr 15, 2026',
 isoDate: '2026-04-15',
 readTime: '6 min read',
 },
 {
 slug: 'your-love-life-in-the-fire-horse-year',
 title: 'Your Love Life in the Fire Horse Year: What Every Sign Needs to Know',
 excerpt: 'The Fire Horse doesn\u2019t care how solid you think your relationship is. Here\u2019s what it actually means for your sign, and what to do about it.',
 categories: ['Romance', 'Year of the Fire Horse'],
 date: 'Apr 15, 2026',
 isoDate: '2026-04-15',
 readTime: '7 min read',
 },
 {
 slug: 'swift-kelce-wedding-stars',
 title: 'What the Stars Actually Say About the Swift-Kelce Wedding',
 excerpt: 'Every Chinese astrology expert says two snakes is a bad match. But when you look at the elements - not just the signs - the charts tell a completely different story.',
 categories: ['Romance', 'Chinese Astrology'],
 date: 'Apr 13, 2026',
 isoDate: '2026-04-13',
 readTime: '6 min read',
 },
 {
 slug: 'love-in-the-fire-horse-year',
 title: 'Love in the Year of the Fire Horse: What 2026 Means for Your Relationships, Sign by Sign',
 excerpt: 'This is the one year in 60 where your partner is most likely to cheat and most likely to propose. Record proposals. Record divorces. The Fire Horse doesn\'t do anything halfway.',
 categories: ['Romance', 'Year of the Fire Horse'],
 date: 'Apr 6, 2026',
 isoDate: '2026-04-06',
 readTime: '8 min read',
 },
 {
 slug: 'who-has-the-most-luck-in-the-fire-horse-year',
 title: 'Who Has the Most Luck in 2026, Fire Horse Year? (And Why That\'s the Wrong Question)',
 excerpt: 'Tiger, Dog, and Sheep have the best alignment. But luck is not something that happens to you. It\'s something you create, and the Fire Horse rewards boldness.',
 categories: ['Year of the Fire Horse', 'Chinese Astrology'],
 date: 'Apr 5, 2026',
 isoDate: '2026-04-05',
 readTime: '5 min read',
 },
 {
 slug: 'blood-moon-rising-in-the-year-of-the-fire-horse',
 title: 'A Once-in-a-Generation Blood Moon Signal Just Landed on the Most Volatile Year in the Chinese Zodiac',
 excerpt: 'A blood moon in the first lunar month has only happened twice in the last hundred years. The last time was 2007. This time it\'s amplified by the Fire Horse.',
 categories: ['Chinese Astrology', 'Year of the Fire Horse'],
 date: 'Apr 4, 2026',
 isoDate: '2026-04-04',
 readTime: '5 min read',
 },
];
