#!/usr/bin/env python3
"""
Generate website/data/purple-star-stars.json — the runtime read-model for the
Purple Star star-identity layer (PR1).

Inputs:
  - /tmp/iztro_catalog.json : every star iztro can emit, as {iztroKey, hanzi, iztroGroup}
                              (generated by a node dump of iztro zh-CN vs en-US)
  - OVERLAY (below)         : hand-authored human knowledge — Bill's names + statuses,
                              the Kwok Man-Ho legacy aliases, element, court role.

Machine-generated (never hand-typed): hanzi, pinyin.
Hand-authored (the overlay): name, nameStatus, legacyAlias, element, courtRole, billKind.

The DB table purple_star_stars is the canonical editable store; this JSON is the
generated read-model the app imports. Regenerate after the source changes.

Display contract (enforced by lib/purpleStarNames.js): show `name` only when
nameStatus == 'locked'; otherwise fall back to `"<pinyin> <hanzi>"`. Draft/resting
names live here for the editor + Bill's review but are NOT shown publicly yet.
"""
import json

CATALOG = json.load(open("/tmp/iztro_catalog.json"))

# Overlay keyed by iztro en-name (the stable runtime join key).
# Fields omitted default to: name=None, nameStatus="unnamed", legacyAlias=None,
# element=None, courtRole=None, billKind from iztroGroup.
OVERLAY = {
    # ---- 14 Major Stars ----
    "emperor":   {"name": "Purple Star", "nameStatus": "locked",  "element": "Yin Earth",  "courtRole": "Emperor — the controlling will",        "legacyAlias": "Purple Star",       "billKind": "Major"},
    "advisor":   {"name": "The Matrix",  "nameStatus": "locked",  "element": "Yin Wood",   "courtRole": "the workings/mechanism of the court",   "legacyAlias": "Heavenly Secret",   "billKind": "Major"},
    "sun":       {"name": "The Sun",     "nameStatus": "locked",  "element": "Yang Fire",  "courtRole": "the force / energy",                    "legacyAlias": "Sun",               "billKind": "Major"},
    "general":   {"name": "Barrel / Chamber",        "nameStatus": "draft",   "element": "Yin Metal",  "courtRole": "the crystallizer / barrel",     "legacyAlias": "Military Music",    "billKind": "Major"},
    "fortunate": {"name": None,                       "nameStatus": "resting", "element": "Yang Water", "courtRole": "equilibrium / balance",         "legacyAlias": "Heavenly Unity",    "billKind": "Major"},
    "judge":     {"name": "Righteous Moral Energy",   "nameStatus": "draft",   "element": "Yin Fire",   "courtRole": "the standard / propriety",       "legacyAlias": "Pure Virtue",       "billKind": "Major"},
    "empress":   {"name": "Treasury",                 "nameStatus": "draft",   "element": "Yang Earth", "courtRole": "the treasury / finance minister","legacyAlias": "Southern Star",     "billKind": "Major"},
    "moon":      {"name": "Moon",                     "nameStatus": "draft",   "element": "Yin Water",  "courtRole": "the revenue collector",         "legacyAlias": "Moon",              "billKind": "Major"},
    "wolf":      {"name": None,                       "nameStatus": "unnamed", "element": "Yang Wood",  "courtRole": "desire / drive",                "legacyAlias": "Greedy Wolf",       "billKind": "Major"},
    "advocator": {"name": "The Voice",                "nameStatus": "draft",   "element": "Yin Water",  "courtRole": "the spokesman / mouth",         "legacyAlias": "Great Door",        "billKind": "Major"},
    "minister":  {"name": "Prime Minister",           "nameStatus": "draft",   "element": "Yang Water", "courtRole": "keeper of the seal",            "legacyAlias": "Heavenly Minister", "billKind": "Major"},
    "sage":      {"name": None,                       "nameStatus": "unnamed", "element": "Yang Earth", "courtRole": "the sheltering beam",            "legacyAlias": "Heavenly Roof-Beam","billKind": "Major"},
    "marshal":   {"name": "Marshal",                  "nameStatus": "draft",   "element": "Yin Metal",  "courtRole": "the commander",                 "legacyAlias": "Seven Killings",    "billKind": "Major"},
    "rebel":     {"name": "Vanguard",                 "nameStatus": "draft",   "element": "Yin Water",  "courtRole": "the demolitionist",             "legacyAlias": "Broken Army",       "billKind": "Major"},
    # ---- Secondary stars Bill's sheet classes as "Major" ----
    "artist":    {"legacyAlias": "Literary Star - Music",            "billKind": "Major"},
    "scholar":   {"legacyAlias": "Literary Star - Literature",       "billKind": "Major"},
    "impulsive": {"legacyAlias": "Fire Star",                         "billKind": "Major"},
    "spark":     {"legacyAlias": "Bell Star",                         "billKind": "Major"},
    "driven":    {"legacyAlias": "Sheep Star (Destruction)",          "billKind": "Major"},
    "tangled":   {"legacyAlias": "Hump-Back Star (Obstruction)",      "billKind": "Major"},
    # ---- Minor / assisting stars ----
    "assistant": {"legacyAlias": "Heavenly Leader",   "billKind": "Minor"},
    "aide":      {"legacyAlias": "Heavenly Halberd",  "billKind": "Minor"},
    "money":     {"legacyAlias": "Heavenly Store",    "billKind": "Minor"},
    "helper":    {"legacyAlias": "Right Assistant",   "billKind": "Minor"},
    "officer":   {"legacyAlias": "Left Assistant",    "billKind": "Minor"},
    "horse":     {"legacyAlias": "Traveling Star",    "billKind": "Minor"},
    "ideologue": {"legacyAlias": "Heavenly Void",     "billKind": "Minor"},
    "fickle":    {"legacyAlias": "Earth Robbery",     "billKind": "Minor"},
    "attractive":{"legacyAlias": "Red Phoenix",       "billKind": "Minor"},
    "cheerful":  {"legacyAlias": "Heavenly Happiness", "billKind": "Minor"},
    "social":    {"legacyAlias": "Heavenly Beauty",   "billKind": "Minor"},
    "serious":   {"legacyAlias": "Heavenly Punishment","billKind": "Minor"},
}

GROUP_TO_KIND = {"majorStars": "Major", "minorStars": "Minor", "adjectiveStars": "Adjective"}


def make_pinyin(hanzi):
    from pypinyin import pinyin, Style
    syl = [s[0] for s in pinyin(hanzi, style=Style.TONE)]
    return " ".join(w[:1].upper() + w[1:] for w in syl if w)


rows = []
for s in CATALOG:
    key, hanzi, group = s["iztroKey"], s["hanzi"], s["iztroGroup"]
    ov = OVERLAY.get(key, {})
    rows.append({
        "iztroKey": key,
        "hanzi": hanzi,
        "pinyin": make_pinyin(hanzi),
        "billKind": ov.get("billKind", GROUP_TO_KIND.get(group, "Adjective")),
        "element": ov.get("element"),
        "courtRole": ov.get("courtRole"),
        "name": ov.get("name"),
        "nameStatus": ov.get("nameStatus", "unnamed"),
        "legacyAlias": ov.get("legacyAlias"),
    })

# Stable order: Major, Minor, Adjective; then by pinyin.
order = {"Major": 0, "Minor": 1, "Adjective": 2}
rows.sort(key=lambda r: (order.get(r["billKind"], 3), r["pinyin"]))

out = "/Users/davepro/code-projects/mahjong-tarot/website/data/purple-star-stars.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump(rows, f, ensure_ascii=False, indent=2)
    f.write("\n")

locked = [r for r in rows if r["nameStatus"] == "locked"]
print(f"wrote {len(rows)} stars → {out}")
print(f"  locked names: {[r['name'] for r in locked]}")
print(f"  with legacyAlias: {sum(1 for r in rows if r['legacyAlias'])}")
print(f"  unnamed (fallback display): {sum(1 for r in rows if r['nameStatus'] == 'unnamed')}")
